#!/usr/bin/env node

/**
 * tasks-tracker.mjs
 *
 * Reads all task files and generates docs/tasks/TRACKER.md with
 * overall progress, per-category summaries, and per-algorithm detail.
 *
 * Usage:
 *   node scripts/tasks-tracker.mjs
 */

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import {
  TASKS_DIR,
  TRACKER_PATH,
  CATEGORIES,
  listDirs,
  listFiles,
  tryReadFile,
  parseTaskFile,
} from './tasks-shared.mjs';

// ── Progress bar ────────────────────────────────────────────────────────────

function progressBar(ratio, width = 20) {
  const filled = Math.round(ratio * width);
  const empty = width - filled;
  return '█'.repeat(filled) + '░'.repeat(empty);
}

// ── Main ────────────────────────────────────────────────────────────────────

async function main() {
  const categoryStats = [];
  let totalAlgos = 0;
  let totalComplete = 0;
  let totalItems = 0;
  let totalChecked = 0;

  // Collect all data
  for (const category of CATEGORIES) {
    const categoryDir = join(TASKS_DIR, category);
    const files = listFiles(categoryDir).filter(f => f.endsWith('.md')).sort();

    const algos = [];
    let catItems = 0;
    let catChecked = 0;
    let catComplete = 0;

    for (const file of files) {
      const content = tryReadFile(join(categoryDir, file));
      if (!content) continue;

      const parsed = parseTaskFile(content);
      const itemCount = parsed.items.length;
      const checkedCount = parsed.items.filter(i => i.checked).length;
      const isComplete = itemCount > 0 && checkedCount === itemCount;

      algos.push({
        name: parsed.name || file.replace('.md', ''),
        slug: parsed.slug || file.replace('.md', ''),
        file,
        itemCount,
        checkedCount,
        isComplete,
      });

      catItems += itemCount;
      catChecked += checkedCount;
      if (isComplete) catComplete++;
    }

    categoryStats.push({
      category,
      algos,
      algoCount: algos.length,
      completeCount: catComplete,
      items: catItems,
      checked: catChecked,
    });

    totalAlgos += algos.length;
    totalComplete += catComplete;
    totalItems += catItems;
    totalChecked += catChecked;
  }

  // Build markdown
  const pct = totalItems > 0 ? ((totalChecked / totalItems) * 100).toFixed(1) : '0.0';
  const algoPct = totalAlgos > 0 ? ((totalComplete / totalAlgos) * 100).toFixed(1) : '0.0';
  const bar = progressBar(totalItems > 0 ? totalChecked / totalItems : 0, 30);

  let md = `# Task Tracker Dashboard

> Auto-generated by \`npm run tasks:tracker\`. Do not edit manually.

## Overall Progress

**Algorithms:** ${totalComplete} / ${totalAlgos} complete (${algoPct}%)
**Items:** ${totalChecked} / ${totalItems} checked (${pct}%)

\`\`\`
${bar} ${pct}%
\`\`\`

## Category Summary

| Category | Algorithms | Complete | Items Done | Progress |
|----------|-----------|----------|------------|----------|
`;

  for (const cs of categoryStats) {
    const catPct = cs.items > 0 ? ((cs.checked / cs.items) * 100).toFixed(0) : '0';
    const catBar = progressBar(cs.items > 0 ? cs.checked / cs.items : 0, 10);
    md += `| ${cs.category} | ${cs.algoCount} | ${cs.completeCount} | ${cs.checked}/${cs.items} | ${catBar} ${catPct}% |\n`;
  }

  // Per-category detail sections
  for (const cs of categoryStats) {
    if (cs.algoCount === 0) continue;

    md += `\n## ${cs.category}\n\n`;
    md += `| Algorithm | Done | Items | Status |\n`;
    md += `|-----------|------|-------|--------|\n`;

    for (const algo of cs.algos) {
      const status = algo.isComplete ? 'Done' : `${algo.checkedCount}/${algo.itemCount}`;
      const link = `[${algo.name}](./${cs.category}/${algo.file})`;
      md += `| ${link} | ${algo.checkedCount}/${algo.itemCount} | ${algo.itemCount} | ${status} |\n`;
    }
  }

  await writeFile(TRACKER_PATH, md, 'utf-8');
  console.log(`Tracker updated: ${TRACKER_PATH}`);
  console.log(`  ${totalAlgos} algorithms, ${totalChecked}/${totalItems} items checked (${pct}%)`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
