# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  pull_request:
    branches: [ master ]
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      if: github.action == 'closed' && github.pull_request.merged == 'true'
      run: |
        cd scripts 
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python readme_generator.py
    - name: Commit report
      if: github.action == 'closed' && github.pull_request.merged == 'true'
      run: |
        git config --global user.name 'thuva4'
        git config --global user.email 'thuva4@users.noreply.github.com'
        git commit -am "Automated readme update"
        git push
  
